use_frameworks!

platform :ios, '8.0'

target 'af1_Example' do
  pod 'af1', :path => '../'

  target 'af1_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
